/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.inventorymanagementproject;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tranb
 */
public class AddProductWindow extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddProductWindow.class.getName());
    private Connection conn = DatabaseConnection.getConnection();
    

    /**
     * Creates new form AddProductWindow
     */
    public AddProductWindow() {
        initComponents();
        this.setLocationRelativeTo(null);
//        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        insertButton = new javax.swing.JButton();
        nameTextField = new javax.swing.JTextField();
        amountTextField = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        priceTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        insertButton.setText("Insert");
        insertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertButtonActionPerformed(evt);
            }
        });

        nameTextField.setText("Product Name");
        nameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameTextFieldFocusLost(evt);
            }
        });

        amountTextField.setText("Product Amount");
        amountTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                amountTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                amountTextFieldFocusLost(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        priceTextField.setText("Product Price");
        priceTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                priceTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                priceTextFieldFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(insertButton)
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addGap(18, 18, 18)
                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(amountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(insertButton)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void addToInventory(String name, int amount, double price) {
        String setSafetyModeOff = "SET SQL_SAFE_UPDATES = 0;";
        try (PreparedStatement stmt = conn.prepareStatement(setSafetyModeOff)) {
            stmt.executeUpdate();
        } catch (SQLException ex) { 
            System.getLogger(tableWindow.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
        //find if the product is already in the inventory or not.
        //SQL statement will return 0 if no such product is found in inventory
        String ifAlreadyExists = "SELECT itemAmount FROM products WHERE itemName = ?";
        try (PreparedStatement stmt = conn.prepareStatement(ifAlreadyExists)) {
            stmt.setString(1, name);
            try(ResultSet rs = stmt.executeQuery()){
  
            if (rs.next()) {
                // Product exists ==> update amount
                    int currentAmount = rs.getInt("itemAmount");
                    String updateSql = "UPDATE products SET itemAmount = ? WHERE itemName = ?";
                    try (PreparedStatement updateStmt = conn.prepareStatement(updateSql)) {
                        updateStmt.setInt(1, currentAmount + amount);
                        updateStmt.setString(2, name);
                        updateStmt.executeUpdate();
                    }
            } else {
                // Product does not exist ==> insert new row
                    String insertSql = "INSERT INTO products (itemName, itemAmount, itemPrice, dateAdded) VALUES (?,?,?,NOW())";
                    try (PreparedStatement insertStmt = conn.prepareStatement(insertSql)) {
                        insertStmt.setString(1, name);
                        insertStmt.setInt(2, amount);
                        insertStmt.setDouble(3, price);
                        insertStmt.executeUpdate();
                    }
                } 
            }
        } catch (SQLException ex) {
            System.getLogger(tableWindow.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }        
    }
    private boolean productExists(String name) {
        String ifAlreadyExists = "SELECT itemAmount FROM products WHERE itemName = ?";
        try (PreparedStatement stmt = conn.prepareStatement(ifAlreadyExists)) {
            stmt.setString(1, name);
            try(ResultSet rs = stmt.executeQuery()){
                if (rs.next()) {
                    return true;
                } else {
                    return false;
                }
            } 
        } catch (SQLException e) {
            System.getLogger(tableWindow.class.getName()).log(System.Logger.Level.ERROR, (String) null, e);
        }
        return false;
    }
    private void insertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertButtonActionPerformed
        // TODO add your handling code here:
        String n = nameTextField.getText();
        String a = amountTextField.getText();
        String p = priceTextField.getText();
        if (n.equals("Product Name") || a.equals("Product Amount") || !productExists(n)) {
            JOptionPane.showMessageDialog(this, "Please fill out all fields.");
            return;
           }
        int amount;
        double price = 0;
        //check if input into product ordered is integer or not
        // Source - https://stackoverflow.com/a
        // Posted by Ruchira Gayan Ranaweera
        // Retrieved 2025-12-15, License - CC BY-SA 3.0

         try {
           amount = Integer.parseInt(a); 
           if (!productExists(n)) {
               price = Double.parseDouble(p);
           }
         }catch(NumberFormatException e) {
           JOptionPane.showMessageDialog(this, "Please Enter ONLY Integer Values Into Product Ordered And Double Values Into Product Price","Input Error",JOptionPane.ERROR_MESSAGE); 
           nameTextField.setText("");
           return;
         } 
//
//         amount = Integer.parseInt(a);
//         price = Double.parseDouble(p);
         addToInventory(n,amount,price);
         this.dispose();
         
         
         
    }//GEN-LAST:event_insertButtonActionPerformed

    private void nameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTextFieldFocusGained
        // TODO add your handling code here:
        String n = nameTextField.getText();
        if (n.equals("Product Name")) {
            nameTextField.setText("");
        }
    }//GEN-LAST:event_nameTextFieldFocusGained

    private void nameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTextFieldFocusLost
        // TODO add your handling code here:
        String n = nameTextField.getText();
        if (n.equals("")) {
            nameTextField.setText("Product Name");
        }
    }//GEN-LAST:event_nameTextFieldFocusLost

    private void amountTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_amountTextFieldFocusGained
        // TODO add your handling code here:
        String n = amountTextField.getText();
        if (n.equals("Product Amount")) {
            amountTextField.setText("");
        }
    }//GEN-LAST:event_amountTextFieldFocusGained

    private void amountTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_amountTextFieldFocusLost
        // TODO add your handling code here:
        String n = amountTextField.getText();
        if (n.equals("")) {
            amountTextField.setText("Product Amount");
        }
    }//GEN-LAST:event_amountTextFieldFocusLost

    private void priceTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_priceTextFieldFocusGained
        // TODO add your handling code here:
        String n = priceTextField.getText();
        if (n.equals("Product Price")) {
            priceTextField.setText("");
        }
    }//GEN-LAST:event_priceTextFieldFocusGained

    private void priceTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_priceTextFieldFocusLost
        // TODO add your handling code here:
        String n = priceTextField.getText();
        if (n.equals("")) {
            priceTextField.setText("Product Price");
        }
    }//GEN-LAST:event_priceTextFieldFocusLost

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new MainWindow().setVisible(true); 
    }//GEN-LAST:event_backButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AddProductWindow().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountTextField;
    private javax.swing.JButton backButton;
    private javax.swing.JButton insertButton;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField priceTextField;
    // End of variables declaration//GEN-END:variables
}
